### ISSUE TITLE
NullPointerException at start

### ISSUE THREAD

**Issue by retorquere** [ObeoNetwork/UML-Designer#1073]
I've downloaded UML_Designer for MacOS, but it errors out immediately at start with an NPE:

```
!SESSION 2023-03-31 12:03:56.014 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -keyring /Users/emile/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/emile/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2023-03-31 12:03:59.169
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
  at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2176)
  at org.eclipse.swt.graphics.GC.<init>(GC.java:174)
  at org.eclipse.swt.graphics.GC.<init>(GC.java:135)
  at org.eclipse.jface.dialogs.Dialog.initializeDialogUnits(Dialog.java:934)
  at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:142)
  at org.eclipse.jface.window.Window.create(Window.java:426)
  at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
  at org.eclipse.jface.window.Window.open(Window.java:783)
  at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.prompt(ChooseWorkspaceDialog.java:114)
  at org.eclipse.ui.internal.ide.application.IDEApplication.promptForWorkspace(IDEApplication.java:364)
  at org.eclipse.ui.internal.ide.application.IDEApplication.checkInstanceLocation(IDEApplication.java:278)
  at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:141)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by mPorhel** [comment]
Hi, 

Could you give us more details about your version of macOS and the kind of processor your have ? (Intel or Apple Silicon)

UML Designer 9.0 was built on top of Eclipse Oxygen, it might no longer be compatible with recent versions of macOS.

Regards

**Comment by retorquere** [comment]
Sorry:

![image](https://user-images.githubusercontent.com/132108/229097712-2e5baf87-c00b-4f5f-af9e-1fdaa3751c52.png)

I'm running Ventura 13.2.1

**Comment by retorquere** [comment]
So should I install latest bare-bones eclipse and load UML-Designer into it as an extension?

**Comment by mPorhel** [comment]
I would have tried this. 
But it seems that the update site and the features/plugins it contains might have dependencies issues with latest Eclipse versions. 
I was unable to install UML Designer on a fresh Eclipse IDE for Eclipse Committers packages 2023-03.

**Comment by mPorhel** [comment]
Hi Emiliano, 

UML Designer is currently no more supported. 

The underlying Eclipse Platform version is no more compatible with the recent versions of macOS.
The Windows product might still work if you have access to a Windows VM or computer.

Regards

**Comment by retorquere** [comment]
I don't. Shame. Surprising there are so few options for this kind of tool!
