### ISSUE TITLE
[Sys2Soft/4.2] unable to apply the standard UML profile to a UML model

### ISSUE THREAD

**Issue by jer-TRT** [ObeoNetwork/UML-Designer#511]
UML Designer 4.0.1

![bug- standard profile](https://cloud.githubusercontent.com/assets/8522964/4010308/158eb670-29f3-11e4-8b73-b85b6b2c17da.PNG)

NPE : java.lang.NullPointerException
                at org.eclipse.emf.eef.runtime.impl.components.StandardPropertiesEditionComponent.firePropertiesChanged(StandardPropertiesEditionComponent.java:212)
                at org.obeonetwork.dsl.uml2.properties.uml.parts.forms.ProfilesPropertiesEditionPartForm$5.process(ProfilesPropertiesEditionPartForm.java:237)
                at org.eclipse.emf.eef.runtime.ui.widgets.TabElementTreeSelectionDialog.okPressed(TabElementTreeSelectionDialog.java:380)
                at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
                at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
                at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
                at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
                at org.eclipse.jface.window.Window.open(Window.java:808)
                at org.obeonetwork.dsl.uml2.properties.uml.parts.forms.ProfilesPropertiesEditionPartForm.addAppliedProfiles(ProfilesPropertiesEditionPartForm.java:246)
                at org.obeonetwork.dsl.uml2.properties.uml.parts.forms.ProfilesPropertiesEditionPartForm$2.handleAdd(ProfilesPropertiesEditionPartForm.java:140)
                at org.eclipse.emf.eef.runtime.ui.widgets.ReferencesTable$AddButtonlistener.mouseUp(ReferencesTable.java:563)
                at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:220)
                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
                at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
                at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
                at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by fbats** [comment]
could not be reproduced in 5.0.0

**Comment by mbats** [comment]
Fixed in 5.0.0
