### ISSUE TITLE
Exception thrown when cancelling dialogs

### ISSUE THREAD

**Issue by Kellindil** [ObeoNetwork/UML-Designer#839]
This was observed on UML Deisgner 7.0.0.201603291431 installed in a fresh Neon RC1
1. import the Travel Agency example (File > New > Example... > Travel Agency UML)
2. open the "Entitites" class diagram
3. hover the mouse on "Customer" and select the "typed property" tool.
4. Cancel the dialog that opens

Another dialog opens to tell that some elements have to be deleted. Cancel it as well. The following exception is thrown :
org.obeonetwork.dsl.uml2.design.internal.dialogs.CancelOperationException: Deletion operation canceled
    at org.obeonetwork.dsl.uml2.design.internal.triggers.ConfirmDeletionTrigger.localChangesAboutToCommit(ConfirmDeletionTrigger.java:116)
    at org.eclipse.sirius.business.internal.session.SessionEventBrokerImpl.transactionAboutToCommit(SessionEventBrokerImpl.java:205)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl$1PrecommitRunnable.run(TransactionalEditingDomainImpl.java:652)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:328)
    at org.eclipse.emf.transaction.util.TransactionUtil.runExclusive(TransactionUtil.java:328)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl$1PrecommitRunnable.runExclusive(TransactionalEditingDomainImpl.java:626)
    at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.precommit(TransactionalEditingDomainImpl.java:696)
    at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:414)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:155)
    at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
    at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
    at org.eclipse.sirius.diagram.ui.tools.internal.commands.WrappingCommandIgnoringAffectedFiles.execute(WrappingCommandIgnoringAffectedFiles.java:124)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
    at org.eclipse.sirius.diagram.ui.tools.internal.editor.DDiagramCommandStack.execute(DDiagramCommandStack.java:71)
    at org.eclipse.sirius.diagram.ui.tools.internal.editor.DDiagramCommandStack.execute(DDiagramCommandStack.java:52)
    at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramCommandStack.execute(DiagramCommandStack.java:156)
    at org.eclipse.gef.tools.AbstractTool.executeCommand(AbstractTool.java:425)
    at org.eclipse.gef.tools.AbstractTool.executeCurrentCommand(AbstractTool.java:438)
    at org.eclipse.gmf.runtime.diagram.ui.tools.AbstractPopupBarTool.performCreation(AbstractPopupBarTool.java:135)
    at org.eclipse.gmf.runtime.diagram.ui.tools.AbstractPopupBarTool.handleButtonUp(AbstractPopupBarTool.java:123)
    at org.eclipse.gef.tools.AbstractTool.mouseUp(AbstractTool.java:1200)
    at org.eclipse.gef.tools.SelectionTool.mouseUp(SelectionTool.java:574)
    at org.eclipse.gef.EditDomain.mouseUp(EditDomain.java:301)
    at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseReleased(DomainEventDispatcher.java:380)
    at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseUp(LightweightSystem.java:548)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:221)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4415)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4233)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3821)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1119)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1020)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by mbats** [comment]
This is due to the ConfirmDeletionTrigger which when the dialog is canceled throw a cancel operation exception in order that EMF transation rollback the changes.

**Comment by AxelRICHARD** [comment]
Fix has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/937
