### ISSUE TITLE
Copy command ended in NPE

### ISSUE THREAD

**Issue by Kellindil** [ObeoNetwork/UML-Designer#840]
I don't know how to reproduce this, but in case there's something obvious...

Caused by: java.lang.NullPointerException
    at org.eclipse.emf.edit.command.CopyCommand.create(CopyCommand.java:64)
    at org.eclipse.emf.edit.command.CopyToClipboardCommand.prepare(CopyToClipboardCommand.java:101)
    at org.eclipse.emf.common.command.AbstractCommand.canExecute(AbstractCommand.java:108)
    at org.eclipse.emf.edit.command.AbstractOverrideableCommand.doCanExecute(AbstractOverrideableCommand.java:114)
    at org.eclipse.emf.edit.command.AbstractOverrideableCommand.canExecute(AbstractOverrideableCommand.java:107)
    at org.obeonetwork.dsl.uml2.editor.internal.CopyCommandHandler.execute(CopyCommandHandler.java:43)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:54)

**Comment by AxelRICHARD** [comment]
We close the bug as we are not able to reproduce it.
