### ISSUE TITLE
Change operation to abstract does not work

### ISSUE THREAD

**Issue by juliendupont** [ObeoNetwork/UML-Designer#843]
The changement method visibility to abstract does not work.
An exception is raised:

An exception was ignored during command execution

org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
    at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.handleError(AbstractTransactionalCommandStack.java:125)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:229)....

Caused by: org.eclipse.emf.transaction.RollbackException: Uncaught exception during pre-commit trigger processing
    at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:213)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
    ... 30 more

**Comment by mbats** [comment]
I tried to reproduce by creating a class diagram with a class and an operation. Then I select the abstract feature. The operation appears in italic in the class and no exception is thrown. Could you detail how to reproduce the stack ?

**Comment by AxelRICHARD** [comment]
We close the bug as we are not able to reproduce it.
