### ISSUE TITLE
JGoogleAnalyticsTracker initialization failure

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#902]
See the stackoverflow question: http://stackoverflow.com/questions/40768078/jgoogleanalyticstracker-initialization-failure-in-uml-designer-plugin
"I am getting a repeated error while using OBEO UML-Designer plugin version 6.0.0.2 for Eclipse Mars. There is a setting in Eclipse Preferences under Windows-Preferences-Sirius-UML Designer Usage - the check box that indicates whether collection of data is allowed or disallowed, in my case the box is unchecked, so it should not attempt to collect the data. However, it appears trying to collect the data and fails for some reason as indicated below:

!ENTRY org.eclipse.ui.workbench 4 2 2016-11-22 15:39:08.529 !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench". !STACK 0 java.lang.NoClassDefFoundError: com.dmurph.tracking.JGoogleAnalyticsTracker (initialization failure) at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:87) at org.obeonetwork.dsl.uml2.usage.analytics.SiriusEditorsListener.(SiriusEditorsListener.java:67) at org.obeonetwork.dsl.uml2.usage.analytics.UsageStartup$1.windowActivated(UsageStartup.java:65)

Multiple occurences of the same error are logged by Eclipse."

**Comment by mbats** [comment]
The exception seems to come from : 
```
static {
        asyncThreadGroup.setMaxPriority(Thread.MIN_PRIORITY);
        asyncThreadGroup.setDaemon(true);
    }
```
As a workaround, we could try to register the listener only when the preference is activated
